global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'node'
    static_configs:
     #- targets: ['http://46.137.11.111:9100']
     - targets: ['46.137.11.111:9100','46.137.11.111:8081']
  #- job_name: 'node-ec2'
  #  ec2_sd_configs:
    #  - region: eu-west-1
    #    access_key: PUT_THE_ACCESS_KEY_HERE
    #    secret_key: PUT_THE_SECRET_KEY_HERE
    #    port: 9100
    # The information to access the EC2 API.

    # The AWS Region.
  #  - region: eu-west-1
    # The AWS API keys. If blank, the environment variables `AWS_ACCESS_KEY_ID`
    # and `AWS_SECRET_ACCESS_KEY` are used.
  #    access_key: AKIAI3FMS27GYR56HCWA
  #    secret_key: AWS_SECRET_ACCESS_KEY=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
    # The port to scrape metrics from. If using the public IP address, this must
    # instead be specified in the relabeling rule.
  #    port: 9100

    # Filters can be used optionally to filter the instance list by other criteria.
    # Available filter criteria can be found here:
    # https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeInstances.html
    # Filter API documentation: https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_Filter.html
    #filters:
    #  [ - name: <string>
    #      values: <string>, [...] ]